services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081" # Metro Bundler[cite: 2]
      - "19000:19000" # Expoサーバー
      - "4040:4040" # ngrok用
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP}
    stdin_open: true
    tty: true
    dns:
      - 8.8.8.8
      - 1.1.1.1
    network_mode: "bridge"

volumes:
  expo_node_modules:
